// The icon registry's name set, shared so callers get compile-time-checked glyphs
// (a typo fails svelte-check rather than rendering nothing).
export type IconName =
  | 'sun'
  | 'moon'
  | 'command'
  | 'search'
  | 'dashboard'
  | 'snippets'
  | 'sftp'
  | 'terminal'
  | 'close'
  | 'hide'
  | 'collapse'
  | 'expand'
  | 'minimize'
  | 'maximize'
  | 'check'
  | 'play'
  | 'edit'
  | 'trash'
  | 'plus'
  | 'folder'
  | 'file'
  | 'upload'
  | 'download'
  | 'refresh'
  | 'key'
  | 'shield'
  | 'ssh-config'
  | 'settings'
  | 'telegram'
  | 'star'
  | 'pin'
  | 'desktop-card';
